spring.threads.virtual.enabled: true
server.port: 8070

coinbase.endpoint: wss://ws-feed.exchange.coinbase.com
coinbase-rest.endpoint: https://api.exchange.coinbase.com
coinbase.matcher-message: '{"type": "subscribe","product_ids": ["BTC-USD","ETH-USD","LTC-USD"],"channels": ["matches"]}'

spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



application.websockets.enabled: true
